### ISSUE TITLE
Plugin doesn't work in Android Studio on Mac

### ISSUE THREAD

**Issue by henengel** [halirutan/IntelliJ-Key-Promoter-X#3]
Hi,
I'm using the plugin in Android Studio on my Mac, and when performing an action, a notification balloon doesn't pop up like on Windows.
Using Android Studio version:

Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by halirutan** [comment]
Would you mind trying to download [prerelease 5.8rc7](https://github.com/halirutan/IntelliJ-Key-Promoter-X/releases/download/v5.8rc7/Key-Promoter-X-5.8rc7.zip) and install it? I fixed some issues and tested it on the latest Android Studio on Mac OS.

**Comment by henengel** [comment]
Sorry for the late reply...
Just installed the version you asked manually, and it's still not working...
Any log or anything else I can send you?

**Comment by halirutan** [comment]
In my tests, it worked and this fix *should* be included in the latest official release. I was sure it works because I could pin down the glitch that prevented the plugin to function properly in Android Studio. I can test it again next week. Be brave until then. I have good hopes that we can make it work.

**Comment by halirutan** [comment]
@henengel I tried it today on Mac OS with

![screen shot 2017-08-28 at 18 20 19](https://user-images.githubusercontent.com/511683/29782689-cab27d4a-8c1d-11e7-9187-60f7fab791b2.png)

and the latest Key Promoter X version 5.8 that is officially available in the Jetbrains repository.

Clicking for instance "Project" with the mouse shows the tooltip.
